### ISSUE TITLE
Check if song is already in queue when adding

### ISSUE THREAD

**Issue by ak505188** [CSUN-Comp490/partyq#176]

**Comment by stefaneng** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find could work for looking through the array

**Comment by marcoajonker** [comment]
check product specs for adding a song. adding duplicates should upvote original and give notie that it has already been added but that it was upvoted

**Comment by ak505188** [comment]
Multiple adds should only give upvote notification once.
