### ISSUE TITLE
facebook share

### ISSUE THREAD

**Issue by marcoajonker** [CSUN-Comp490/partyq#296]

**Comment by marcomarandiz** [comment]
<a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fpartyq.io" + window.location.href><span >fb</span></a>

**Comment by marcomarandiz** [comment]
"<a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fpartyq.io" + window.location.href><span >fb</span></a>"
