### ISSUE TITLE
Create next button and logic

### ISSUE THREAD

**Issue by stefaneng** [CSUN-Comp490/partyq#76]
Need next button handler and next button

**Comment by ak505188** [comment]
Isn't the logic handled in the reducer you made?

**Comment by stefaneng** [comment]
Yeah, just need the button and the connecting handlers and stuff which I called logic. Not sure if there is a better than logic..

**Comment by ak505188** [comment]
I was thinking handler haha. But as long as we know we know what we need it doesn't matter what we call it.

**Comment by stefaneng** [comment]
Closed in #83
