### ISSUE TITLE
Youtube Integration

### ISSUE THREAD

**Issue by ak505188** [CSUN-Comp490/partyq#87]
Stuff we will need for this:
Asynchronous redux #97
Integrate IFrame in CurrentSong #98
Connect Play/Pause/Next Buttons
Autoplay on adding to current song when isPlaying=true

**Comment by stefaneng** [comment]
http://rackt.org/redux/docs/advanced/AsyncActions.html will probably be useful for this

**Comment by marcoajonker** [comment]
song name
artist
upload date
source: youtube
duration

**Comment by ak505188** [comment]
GET https://www.googleapis.com/youtube/v3/videos?part=snippet&id=qUn1tzyTYeo&key={YOUR_API_KEY}

Covers YouTube Title, Youtube Channel Id (not channel name), Upload date & source (obviously)
Does not cover duration but that can be done from the Iframe in current song
